# Generated by Django 5.2 on 2025-04-15 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Terapeuta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('usuario', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=200)),
                ('contapoio', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantidade', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='Terapeuta.terapeuta')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
