# Generated by Django 5.2 on 2025-04-15 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Terapeuta', '0001_initial'),
        ('decano', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('Terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimento', to='Terapeuta.terapeuta')),
                ('decano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimento', to='decano.decano')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimento', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['paciente'],
            },
        ),
    ]
